---
- name: Install greeter
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - greetd
    - greetd-tuigreet
  notify:
    - Start and enable greetd aservice
