---
- name: Install amd gpu driver
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - amd-ucode
    - xf86-video-amdgpu
    - xf86-video-ati
    - vulkan-radeon

