---
- name: Installing AUR helper
  kewlfft.aur.aur:
    name: paru
    state: present

- name: Install basic utillities
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - wl-clipboard
    - brightnessctl
    - fastfetch
    - btop
    - jq
    - bc
