---
- name: Install GUI apps
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - gimp
    - discord

- name: Install GUI apps using AUR
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: paru
  loop:
    - zen-browser-bin
    - spotify
