---
- name: Install dev utilities
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - base-devel
    - curl
    - wget
    - git
    - ghostty
    - nano
    - vim
    - neovim
    - stylua
    - lua51
    - luarocks
    - go

